version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_doc
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/server.crt:/etc/nginx/cert/server.crt
      - ./nginx/cert/server.key:/etc/nginx/cert/server.key 
    depends_on:
      - fastapi_doc
  fastapi_doc:
    build: ./fastapi_app
    container_name: fastapi_doc
    ports: 
      - "8888:8888"
    volumes:
      - ./fastapi_app/app/:/code/app/
      - ./fastapi_app/app/uploads/:/code/app/uploads
      - ./fastapi_app/:/code/
      - ./fastapi_app/requirements.txt:/code/requirements.txt
    environment:
      - DB_USER=doc_tagging
      - DB_PASS=gniggat_cod
      - DB_HOST=128.199.243.160 
      - DB_PORT=5432
      - DB_NAME=doctag
      - API_KEY=akljnv13bvi2vfo0b0bw