version: '3.3'

services:
  fastapi_doc:
    build: ./fastapi_app
    container_name: fastapi_doc
    ports: 
      - "8888:8888"
    volumes:
      - ./fastapi_app/app/:/code/app/
      - ./fastapi_app/:/code/
      - ./fastapi_app/requirements.txt:/code/requirements.txt
    environment:
      - DATABASE_URL=postgresql+asyncpg://doc_tagging:gniggat_cod@128.199.243.160:5432/doctag
      - API_KEY=akljnv13bvi2vfo0b0bw