version: '3.3'

services:
  fastapi_doc:
    build: ./fastapi_app
    container_name: fastapi_doc
    ports: 
      - "8888:8888"
    volumes:
      - ./fastapi_app/app/:/code/app/
      - ./fastapi_app/:/code/
      - ./fastapi_app/requirements.txt:/code/requirements.txt
    environment:
      - DB_USER=doc_tagging
      - DB_PASS=gniggat_cod
      - DB_HOST=128.199.243.160
      - DB_PORT=5432
      - DB_NAME=doctag
      - API_KEY=akljnv13bvi2vfo0b0bw